<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
				<IsPackable>false</IsPackable>
				<IsTestProject>true</IsTestProject>
				<OutputType>Exe</OutputType>
		</PropertyGroup>

		<ItemGroup>
				<PackageReference Include="coverlet.collector">
						<PrivateAssets>all</PrivateAssets>
						<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
				</PackageReference>
				<PackageReference Include="System.Net.Http" />
				<PackageReference Include="Vogen" />
				<PackageReference Include="xunit.v3" />
		</ItemGroup>

		<ItemGroup>
				<ProjectReference Include="..\..\src\Jouska.AutoFixture.Extensions.VogenLib\Jouska.AutoFixture.Extensions.VogenLib.csproj" />
		</ItemGroup>

		<ItemGroup>
				<Using Include="Xunit" />
		</ItemGroup>

</Project>
