<Project>
		<PropertyGroup>
				<ImplicitUsings>enable</ImplicitUsings>
				<Nullable>enable</Nullable>
				<LangVersion>14.0</LangVersion>
				<TreatWarningsAsErrors>true</TreatWarningsAsErrors>
				<CheckEolTargetFramework>false</CheckEolTargetFramework>
				<Deterministic>true</Deterministic>
				<Configurations>Debug;Release</Configurations>
				<Copyright>Copyright © Andrew Morshead 2026</Copyright>
				<GenerateAssemblyConfigurationAttribute>false</GenerateAssemblyConfigurationAttribute>
				<GenerateAssemblyDescriptionAttribute>false</GenerateAssemblyDescriptionAttribute>
				<TestingPlatformDotnetTestSupport>true</TestingPlatformDotnetTestSupport>
				<CodeAnalysisCulture>en-US</CodeAnalysisCulture>
				<DebugType>embedded</DebugType>
				<Authors>Andrew Morshead</Authors>
		</PropertyGroup>
</Project>