<Project Sdk="Microsoft.NET.Sdk">
		
		<PropertyGroup>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="AutoFixture" />
				<PackageReference Include="AutoFixture.AutoNSubstitute" />
				<PackageReference Include="AutoFixture.Idioms" />
		</ItemGroup>

</Project>
