<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="Mockly" />
		<PackageReference Include="System.Net.Http" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Jouska.AutoFixture.Extensions.Http.Helpers\Jouska.AutoFixture.Extensions.Http.Helpers.csproj" />
	</ItemGroup>

    <PropertyGroup>
        <PackageId>Jouska.AutoFixture.Extensions.Http.Mockly</PackageId>
        <PackageVersion>1.0.0</PackageVersion>
        <Title>AutoFixture Extensions - Mockly</Title>
        <Description>Helper package for working with AutoFixture and HttpClients using the Mockly mocking library</Description>
        <Authors>Andrew Morshead</Authors>
        <PackageProjectUrl>https://github.com/RygelXVI/AutoFixtureExtensions</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/RygelXVI/AutoFixtureExtensions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

</Project>
