<Project Sdk="Microsoft.NET.Sdk">
		
		<PropertyGroup>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="AutoFixture" />
				<PackageReference Include="Microsoft.Extensions.Logging" />
				<PackageReference Include="Serilog" />
				<PackageReference Include="Serilog.Extensions.Hosting" />
				<PackageReference Include="Serilog.Sinks.Debug" />
				<PackageReference Include="Serilog.Sinks.InMemory" />
		</ItemGroup>

</Project>
