<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="Microsoft.Extensions.Http" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\AutoFixture.Extensions.Http.Helpers\AutoFixture.Extensions.Http.Helpers.csproj" />
  </ItemGroup>

</Project>
