<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<GenerateSBOM>true</GenerateSBOM>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="AutoFixture" />
				<PackageReference Include="RichardSzalay.MockHttp" />
		</ItemGroup>

		<ItemGroup>
				<ProjectReference Include="..\AutoFixture.Extensions.Http.Helpers\AutoFixture.Extensions.Http.Helpers.csproj" />
		</ItemGroup>

</Project>
