<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoFixture" />
    <PackageReference Include="RichardSzalay.MockHttp" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\AutoFixture.Extensions.Http.Helpers\AutoFixture.Extensions.Http.Helpers.csproj" />
  </ItemGroup>

</Project>
