<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="Mockly" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\AutoFixture.Extensions.Http.Helpers\AutoFixture.Extensions.Http.Helpers.csproj" />
	</ItemGroup>

</Project>
