<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
        <TargetFrameworks>netstandard2.0;net8.0;net9.0;net10.0</TargetFrameworks>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>
	<ItemGroup>
	  <ProjectReference Include="..\Jouska.AutoFixture.Extensions.Http.Helpers\Jouska.AutoFixture.Extensions.Http.Helpers.csproj" />
	</ItemGroup>

    <PropertyGroup>
        <PackageId>Jouska.AutoFixture.Extensions.Http</PackageId>
        <PackageVersion>1.0.0</PackageVersion>
        <Title>AutoFixture Extensions - Http</Title>
        <Description>Helper package for working with AutoFixture and HttpClients</Description>
        <Authors>Andrew Morshead</Authors>
        <PackageProjectUrl>https://github.com/RygelXVI/AutoFixtureExtensions</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/RygelXVI/AutoFixtureExtensions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

</Project>
