<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <IsPackable>false</IsPackable>
        <IsTestProject>true</IsTestProject>
        <OutputType>Exe</OutputType>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="AutoFixture" />
        <PackageReference Include="coverlet.collector">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="xunit.v3" />
        <PackageReference Include="Imposter" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\..\src\Jouska.AutoFixture.AutoImposter\Jouska.AutoFixture.AutoImposter.csproj" />
      <ProjectReference Include="..\Jouska.AutoFixture.AutoImposter.TestHelpers\Jouska.AutoFixture.AutoImposter.TestHelpers.csproj" />
    </ItemGroup>

</Project>
