<Project Sdk="Microsoft.NET.Sdk">
		<PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="AutoFixture" />
		<PackageReference Include="NServiceBus.Testing" />
		<PackageReference Include="System.Security.Cryptography.Xml" />
	</ItemGroup>

    <PropertyGroup>
        <PackageId>Jouska.AutoFixture.Extensions.NServiceBus</PackageId>
        <PackageVersion>1.0.0</PackageVersion>
        <Title>AutoFixture Extensions - NServiceBus</Title>
        <Description>Helper package for working with AutoFixture and NServiceBus</Description>
        <Authors>Andrew Morshead</Authors>
        <PackageProjectUrl>https://github.com/RygelXVI/AutoFixtureExtensions</PackageProjectUrl>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <RepositoryUrl>https://github.com/RygelXVI/AutoFixtureExtensions</RepositoryUrl>
        <RepositoryType>git</RepositoryType>
        <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
        <IncludeSymbols>true</IncludeSymbols>
        <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    </PropertyGroup>

</Project>
