<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
        <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
				<IsPackable>false</IsPackable>
				<IsTestProject>true</IsTestProject>
				<OutputType>Exe</OutputType>
		</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="coverlet.collector">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
		</PackageReference>
		<PackageReference Include="NSubstitute" />
		<PackageReference Include="xunit.v3" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\..\src\Jouska.AutoFixture.Extensions.Serilog\Jouska.AutoFixture.Extensions.Serilog.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Xunit" />
	</ItemGroup>

</Project>
