<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
				<GenerateSBOM>true</GenerateSBOM>
				<EnablePackageValidation>true</EnablePackageValidation>
		</PropertyGroup>
		<ItemGroup>
				<PackageReference Include="AutoFixture" />
				<PackageReference Include="Microsoft.Extensions.Options" />
		</ItemGroup>

</Project>
